### ISSUE TITLE
Missaligned layout in list items

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#120]
In Target list, in list mode, change the layout to be similar to the layout of Agent in list mode:
- Remove the 3 dots menu
- Remove the List of domains
- Instead of the list of domains, add the action buttons: Delete | Details | Edit. Each button will execute the corresponding action

![image](https://user-images.githubusercontent.com/4720000/108584609-5e106f00-7308-11eb-831b-43c9a88e84f2.png)

![image](https://user-images.githubusercontent.com/4720000/108584612-6ec0e500-7308-11eb-8095-2271df739576.png)

**Comment by gorums** [comment]
@YanetABUC I agree

**Comment by YanetABUC** [comment]
Working as expected
![image](https://user-images.githubusercontent.com/4720000/123727097-b5928e80-d856-11eb-846a-7ed5824f8f2d.png)
