### ISSUE TITLE
Enhancements in Target List, homepage

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#122]
- [x] In Home page, the list of a Target's root domain list can be long, so intead of displaying the list, display the following text: **Root domains: X**, where X is the number of root domains associated with the selected Target
![image](https://user-images.githubusercontent.com/4720000/108585324-8058bb80-730d-11eb-97e4-d7320bafff2b.png)

- [x] Change the style of the icon to get it align with the style of the Target's icon in Target list, list mode

![image](https://user-images.githubusercontent.com/4720000/108585394-f6f5b900-730d-11eb-909b-ea9d71addc2a.png)

**Comment by YanetABUC** [comment]
@gorums  If you approve this enhancement, then following ticket will go to Won't Fix: https://github.com/reconness/reconness-frontend/issues/123

**Comment by gorums** [comment]
@YanetABUC lets do it in this way

**Comment by YanetABUC** [comment]
Working as expected
![image](https://user-images.githubusercontent.com/4720000/122650769-4dc3a180-d0fa-11eb-8ece-a34414d351f7.png)
