### ISSUE TITLE
Open ports list in Subdomains Details page

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#137]
- In subdomains list, Root Domain Details page, include a comma separrated list with the open port in the selected subdomain. This will appear as a new row in Details column, before the row with label Added. The label of the row will be **Ports:**
![image](https://user-images.githubusercontent.com/4720000/111097361-fb755200-8506-11eb-96b6-179c9acb3cd6.png)

- In Dashboard tab, Subdomain Details page, below the Agents row, insert a new row for the Open ports. The value will be a comma separated list. The label of the row will be **Ports:**

![image](https://user-images.githubusercontent.com/4720000/111097449-252e7900-8507-11eb-84f3-2fbbcab3c207.png)

- The value for the Open ports row will be automatically generated by the system. Ex 
`Ports: 21, 22, 80, 443`

**Comment by YanetABUC** [comment]
@gorums Please, send more info for this tickets

**Comment by gorums** [comment]
@YanetABUC we are going to show the list of Open Ports that the subdomain has here

![image](https://user-images.githubusercontent.com/1503645/109588096-2fe41980-7ad6-11eb-9818-818ed1c15a18.png)

**Comment by gorums** [comment]
Ex
Ports: 21, 22, 80, 443

**Comment by YanetABUC** [comment]
@gorums I added a description to this ticket. Please, check and give me your feedback.

**Comment by YanetABUC** [comment]
![image](https://user-images.githubusercontent.com/4720000/113233391-5bd0f700-925c-11eb-8722-56933d586d91.png)

![image](https://user-images.githubusercontent.com/4720000/113233418-65f2f580-925c-11eb-9f15-c96558f9f42f.png)
