### ISSUE TITLE
Services list in Subdomain Details page

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#139]
### Mockups
![image](https://user-images.githubusercontent.com/4720000/109586645-3caf4000-7acb-11eb-97f1-12e10d08dcb6.png)

### Specifications
1. The services list will contain the following columns:
- Name
- Port: Display the port name from which the service ran (Disclaimer: The name of the column is wrong in the Design prototype)

2. The services tab title will include the total amout of services included in the list.
3. Every column of the list will contain arrows to sort the data ascending or descending
4. The list will have a paginator, if needed
5. The data for this list will be populated automatically everytime the user ran an agent on a subdomain.

**Comment by YanetABUC** [comment]
@gorums Please, answer the following questions:
- How is going to be populated this list?
- Last Run column should display the date of the last run or the value of a port?

**Comment by gorums** [comment]
> @gorums Please, answer the following questions:
> 
> * How is going to be populated this list?
We get that data running the agents, is not a manually thing
> * Last Run column should display the date of the last run or the value of a port?
Is not ```Last Run```, is ```Port```. We only have two columns the Service Name and the Port

**Comment by YanetABUC** [comment]
@gorums Please, check again and give me your feedback

**Comment by YanetABUC** [comment]
![image](https://user-images.githubusercontent.com/4720000/112794184-be8b7e00-9023-11eb-8be9-6e2eedf36001.png)
