### ISSUE TITLE
Directories list in Subdomain Details page

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#140]
### Mockups
![image](https://user-images.githubusercontent.com/4720000/109586777-826c0880-7acb-11eb-9cc7-3daf25f7e7b0.png)

### Specifications
1. The directories list will contain the following columns:
- Directories: Directory path
- Method: Ex: GET
- Status code: Ex: 301
- Size: Value in KB

2. The directories tab title will include the total amout of directories included in the list.
3. Every column of the list will contain arrows to sort the data ascending or descending
4. The list will have a paginator, if needed

**Comment by YanetABUC** [comment]
@gorums Please, provide the list of possible values for Status code and Method columns.
- How is going to be populated this list?

**Comment by gorums** [comment]
@YanetABUC  we got that data from the Agents.

**Comment by YanetABUC** [comment]
![image](https://user-images.githubusercontent.com/4720000/112801700-7160d980-902e-11eb-9ed2-f35589d817c9.png)

There is a style issue to be fixed in #189
