### ISSUE TITLE
Create Pipeline: Settings

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#145]
### Mockups
**Step 3: Settings**
![image](https://user-images.githubusercontent.com/4720000/113553322-370eb380-95bd-11eb-8ae1-d48f07885530.png)

### Specifications
1. The last step in the pipeline creation wizard is for pipeline settings. 
2. Done button will be disabled until there is at least ONE location configured. The Schedule section is optional as a pipeline can be run on demand and not by just scheduling it.
3. Clicking Done button in Pipeline Settings popup, during create pipeline process will open the Pipeline Details screen, described in #146 
4. If user clicks Cancel button, the whole process will be aborted, no new pipeline will be created and the wizard will be closed.
5. Location section - Described in #219 - **Note: The Search blue label is just a label. It is not a button**
6. Schedule section - Described in #218

**Comment by YanetABUC** [comment]
@gorums Some questions here:
- In Settings step, the user needs to pick a location to run the pipeline. The location can be Target, Root Domain and/or a subdomain but in the first step the user can pick any kind of agent, no matter its type. Is this OK? I mean, an Agent typed as Target can be run in a Root Domain or in a Subdomain? Is it possible to have different types of Agents in the same pipeline?
- In this step, the Run button that appear in the image at the top left corner, will have the functionality of somehow test or run the still un-created pipeline??? Or the image is there just for decoration purpose?
- I didn't describe the Search "button" because I guess is just a label, but I'm not sure, because normally in the design all labels are in gray color, so I guess this Search button will have some functionality but I'm not sure if this Search is for an Advanced Search or just a normal Search. If the button does a normal search it can be meaningless as you can do it on the fly, as described.

**Comment by gorums** [comment]
@YanetABUC 
1- If we select Target as pipeline type, that means that the first Agent selected needs to be a Target Agent, the same for the other types [rootDomain, Subdomain]. 

``
In this step, the Run button that appear in the image at the top left corner, will have the functionality of somehow test or run the still un-created pipeline??? Or the image is there just for decoration purpose?
``
In the creating only is for decoration purpose

2- Location is optional, if there is not scheduler (that means that in the the time that we run the pipeline manually we need to select the location)

3 - We can user regular expression for the Location. 
 Ex.  Pipeline Type: Subdomain, location: *.yahoo.com (that means that we are going to run the pipeline for each subdomain that is going to match that regexp, like www.yajoo.com, docs.yahoo.com, etc)

4 - Search button looks like a label

5 - Target, RootDomain and Subdomain are radiobutton, not checkbox

**Comment by YanetABUC** [comment]
> 1- If we select Target as pipeline type, that means that the first Agent selected needs to be a Target Agent, the same for the other types [rootDomain, Subdomain].

@gorums if this is needed then we need to change how the pipelines are created because in the first step the user select some agents to include in the pipeline, in the second step the user selects the start agente and in the third step user configures location and schedulers. I guess we will need to start with the configuration step, then select the agents, and then the start agent. Thoughts?

> 4 - Search button looks like a label
@gorums Please advice what whould be done then. And what sill be the functionality of the Search button?

**Comment by gorums** [comment]
> @gorums if this is needed then we need to change how the pipelines are created because in the first step the user select some agents to include in the pipeline, in the second step the user selects the start agente and in the third step user configures location and schedulers. I guess we will need to start with the configuration step, then select the agents, and then the start agent. Thoughts?
@YanetABUC  Yes we can do it in that order, first the setting and then select the agents
> 
> > 4 - Search button looks like a label
> 
> @gorums Please advice what whould be done then. And what will be the functionality of the Search button?
> 
@YanetABUC we dont need a search button (we can keep that as a label), we can use autocomplete for the location textfield

**Comment by YanetABUC** [comment]
@gorums I'll create another ticket with the reorder in Create pipeline workflow

**Comment by YanetABUC** [comment]
![image](https://user-images.githubusercontent.com/4720000/117545650-4cc42e00-afec-11eb-9391-dd52fa5d2cc7.png)
