### ISSUE TITLE
Pipeline Details page: Workflow section layout

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#148]
### Mockups
![image](https://user-images.githubusercontent.com/4720000/117585536-9722d900-b0d8-11eb-9198-6fe9cb9d0c10.png)

**Agent item's side panel in workflow**
![image](https://user-images.githubusercontent.com/4720000/116016992-f9bda480-a603-11eb-8b92-388b20a6689c.png)

![image](https://user-images.githubusercontent.com/4720000/109589005-45097a00-7acf-11eb-95d8-d3985f8c2bbb.png)

**Add agent below another agent**
![image](https://user-images.githubusercontent.com/4720000/116497241-7f438d80-a86c-11eb-8e19-180b33a826b8.png)

### Specifications
1. The workflow section in Pipeline Details page won't allow drag and drop of element in this first version and won't allow the dynamic reconnection between agents items either. 
2. After closing the Pipeline Settings popup, in the process of create a pipeline, the Workflow section will contain an empty slot to select the starting agent. If user clicks the link, it will appear a dialog with all agents in the workflow that have the same type of the pipeline type, similar to #232
3. Each agent item in the workflow will have a side panel with the following options:
- Remove agent item from workflow: Described in #231
- Insert/Add agent item to workflow: Described in #232
- Configure agent item in the workflow: Described in #152 
4. The side panel will slightly increase its size on mouse hover event.
5. When user does a mouse hover an agent item in the workflow, it will appear a Add button, below the item. Clicking on this Add button  is going to add a new slot for another Agent below, instead in the right, check the images, #232

**Comment by gorums** [comment]
@YanetABUC We need to add too a Button "+ Add" below the Agents, that is going to add a new slot for another Agent below, instead in the right, check the images
Ex.
![image](https://user-images.githubusercontent.com/1503645/116319209-1b459a00-a784-11eb-8e34-85e698fc5f7b.png)
![image](https://user-images.githubusercontent.com/1503645/116319301-462fee00-a784-11eb-906c-51e8cee0994d.png)
![image](https://user-images.githubusercontent.com/1503645/116319397-737c9c00-a784-11eb-9824-cc5cd07d50a1.png)

**Comment by YanetABUC** [comment]
@gorums Please, check this ticket again

**Comment by YanetABUC** [comment]
Working as expected
![image](https://user-images.githubusercontent.com/4720000/119238095-12878000-bb06-11eb-960c-85585889a1f2.png)

![image](https://user-images.githubusercontent.com/4720000/119238099-1e734200-bb06-11eb-8b2a-49fceae5290b.png)
