### ISSUE TITLE
Run pipeline - Terminal

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#153]
### Mockups
![image](https://user-images.githubusercontent.com/4720000/109593737-260ee600-7ad7-11eb-8eed-2feaa1461acb.png)

![image](https://user-images.githubusercontent.com/4720000/109593784-3d4dd380-7ad7-11eb-8f90-b9f3f5902de0.png)

![image](https://user-images.githubusercontent.com/4720000/123738105-d0bac980-d869-11eb-90ea-039c0e59ea4b.png)

![image](https://user-images.githubusercontent.com/4720000/109593847-58b8de80-7ad7-11eb-820a-653152dea8b2.png)

![image](https://user-images.githubusercontent.com/4720000/109593882-6b331800-7ad7-11eb-9b76-435d7c56c1b5.png)

### Specifications
1. User can click on Show Terminal at any moment, before run a pipeline, when the pipeline is running or when the pipeline finished.
2. When user clicks on Show Terminal link, its text will toggle to Hide Terminal
3. Clicking on Hide Terminal link will redirect user to Pipeline Run screen (#151 ) and the user will continue tracking the status of the execution from there
4. In Terminal screen, the button for start the execution of a pipeline will be enable if and only if the pipeline has a defined location.
5. If there is no a location defined, then Start or Run button will be disabled, ,and a notification message will appear indicating the user that he/she needs to define a location by clicking on Pipeline Settings option
6. Terminal screen will contain the following elements:

- Return Arrow. If user clicks here, he/she will be redirected to Pipeline list screen and the pipeline will continue executing in background mode
- Pipeline name
- Menu items:
   - Hide Terminal 
   - Pipeline Settings: Clicking here will open the Pipeline Settings popup
   - Cancel: Clicking here will stop the execution of the pipeline and user will be redirected to the Pipeline Workflow view
- Progress bar indicating the state of the process
- A timer, indicating how much time the pipeline have been ran
- A button to start or stop the process.
    - If there is a location defined, the Start button will be enabled.
    - If there is no location defined, there will be a visible note, indicating the user that he/she needs to define a location before execute the pipeline and the Start button will be disabled until the conditions are met.
- Below the progress bar it will appear the terminal with the outup of the execution of every agent (See Mockups section). Please, remove the play/pause button
- At the right, it will appear a column with all the agents within the pipeline. Agent will be ordered according to its position within the pipeline
- Inside each agent item, will appear links Terminal and Logs.
   - Clicking on them will display a popup with the terminal of the execution results per Agent.
   - Terminal and Logs popups can be opened only if the agent is been executed at that moment or if it was already executed.
   - If an agent is waiting to be executed those links will be disabled.
- If user clicks on Terminal arrow, the content of the main Terminal will change to display the logs and the subtitle will change to Logs

NOTE: We can have more than one agent running at the same time. That means that we need to allow click for all the Agents in the right vertical list to see the Terminal/Logs if it is running or ran before.

**Comment by gorums** [comment]
@YanetABUC that looks really good, and remember we can have more than one agent running at the same time. That means that we need to allow click for all the Agents in the right vertical list to see the Terminal/Logs.

**Comment by YanetABUC** [comment]
![image](https://user-images.githubusercontent.com/4720000/126078708-011d61a5-d074-43c3-ad83-fa93cb444eda.png)

There are some bugs that are going to be tracked in separate tickets:
- https://github.com/reconness/reconness-frontend/issues/291
- https://github.com/reconness/reconness-frontend/issues/292
- https://github.com/reconness/reconness-frontend/issues/293
- https://github.com/reconness/reconness-frontend/issues/294
