### ISSUE TITLE
Missing Remove buttons in Add Subdomain popup

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#163]
### Expected scenario
**Clicking on Remove button (red round button), will remove all the row from the popup.**
![image](https://user-images.githubusercontent.com/4720000/111044679-a276c280-840f-11eb-80c4-fca76dc7d42e.png)

### Current scenario
![image](https://user-images.githubusercontent.com/4720000/111044697-c20deb00-840f-11eb-8212-a210e4def21c.png)

**Comment by YanetABUC** [comment]
@lcc1289 Remove the delete button from the first row, please
![image](https://user-images.githubusercontent.com/4720000/113543316-b98e7780-95ab-11eb-8c05-ef717eec217f.png)

**Comment by YanetABUC** [comment]
![image](https://user-images.githubusercontent.com/4720000/113544756-8699b300-95ae-11eb-80d1-9beeddbf2fe6.png)

**Comment by gorums** [comment]
@YanetABUC 
![image](https://user-images.githubusercontent.com/1503645/113638225-5c92d000-9644-11eb-8095-5b558f74c714.png)
Is not removing the first one
And allow add invalid url
