### ISSUE TITLE
Pipeline Details page: Workflow section - Remove Agent Item from workflow

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#231]
### Mockups
**Remove agent from workflow**
![image](https://user-images.githubusercontent.com/4720000/109592588-1c847e80-7ad5-11eb-997c-6489311cdb99.png)

**After removing the starting agent**
![image](https://user-images.githubusercontent.com/4720000/116497061-18be6f80-a86c-11eb-9ced-8515c40c7dc7.png)

### Specifications
1. If there is only one element in the workflow, the Remove agent item button, in the side panel, will be disabled. There will be always at least one agent item in the workflow
2. When user clicks on the Remove button, a confirmation popup will be displayed. The text in the confirmation popup is the following: _Please, confirm if you want to remove agent **[agent_name]** from the pipeline's workflow_. The confirmation popup will have 2 buttons: Confirm and Cancel
- If user press Confirm, the agent item will be removed from the workflow and the confirmation popup will be closed
- If user press Cancel, the confirmation popup will be closed and no action will be executed
3. The proccess of removing an agent item from the workflow will be as follows:
- If the item to be removed is the **first** one in the workflow, then it will appear an empty slot with a link "Add starting agent" inside of it. If user clicks the link, it will appear a dialog with all agents in the workflow that have the same type of the pipeline type, similar to #232 
- If the item to be removed is the **last** one in the workflow, then the item previous to it, in the workflow, is going to be the last agent 
- If the item to be remove is within the workflow (not the first or last item), then its adjacent items will be linked directly
4. A pipeline workflow is like a linked queue
5. After removing an agent item, the conectors will be updated accordingly

**Comment by YanetABUC** [comment]
@gorums I can't decide if we are going to allow the user to remove the first element. The pipeline's type is set according to the first agent's type. I can't find a simple solution to keep this assertion if we allow the removal of the first agent item. Thoughts?

**Comment by gorums** [comment]
@YanetABUC we can remove the first Agent, but we need to keep that empty instead moving the second to that slot and we need to add a new one base of the pipeline type (Target, rootdomain, subdomain) [require]

**Comment by YanetABUC** [comment]
@gorums Please check this ticket again

**Comment by YanetABUC** [comment]
Working as expected

![image](https://user-images.githubusercontent.com/4720000/119239582-ae69b980-bb0f-11eb-8cb3-4f54cb63c433.png)

![image](https://user-images.githubusercontent.com/4720000/119239606-d35e2c80-bb0f-11eb-813f-e5e7e956deb5.png)

![image](https://user-images.githubusercontent.com/4720000/119239656-2b952e80-bb10-11eb-847d-698fed3fa7b4.png)

![image](https://user-images.githubusercontent.com/4720000/119239663-36e85a00-bb10-11eb-8a74-128f4c0c6eae.png)

![image](https://user-images.githubusercontent.com/4720000/119239676-47003980-bb10-11eb-9149-b7be28977d35.png)

![image](https://user-images.githubusercontent.com/4720000/119239684-51223800-bb10-11eb-9b19-27cdaba3f313.png)
