### ISSUE TITLE
Pipeline Details page: Workflow section -  Insert/Add agent item to workflow

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#232]
### Mockups
**Add agent to workflow**
![image](https://user-images.githubusercontent.com/4720000/117585681-52e40880-b0d9-11eb-9182-c6a1148bf6bd.png)

**Examples of how to include a new Add button below every agent in the workflow**
![image](https://user-images.githubusercontent.com/4720000/116497241-7f438d80-a86c-11eb-8e19-180b33a826b8.png)
![image](https://user-images.githubusercontent.com/4720000/116497411-e5c8ab80-a86c-11eb-9809-486c0661cbcb.png)

![image](https://user-images.githubusercontent.com/1503645/116319209-1b459a00-a784-11eb-8e34-85e698fc5f7b.png)
![image](https://user-images.githubusercontent.com/1503645/116319301-462fee00-a784-11eb-906c-51e8cee0994d.png)
![image](https://user-images.githubusercontent.com/1503645/116319397-737c9c00-a784-11eb-9824-cc5cd07d50a1.png)

**Select agent to workflow**
![image](https://user-images.githubusercontent.com/4720000/116191506-0d473900-a6f2-11eb-9f18-427e2ec306c7.png)

### Specifications
1. Clicking on Insert agent item button, will display the popup that appear in the Mockups section:
- The popup will contain the agents in the pipeline and the user will be able to select just one.
- Done button will be disable if there is no agent selected
- If the user clicks Done button, the agent will be inserted after the item which insert button was clicked, the connectors will be updated accordingly and the popup will be closed
- If the user clicks the Close button, the popup will be closed and no item will be inserted
2. No item will be inserted before the starting agent item
3. An agent can be included in the workflow more than once
4. The user can insert into the workflow, as many agents as he/she wants
5. When user does a mouse hover an agent item in the workflow, it will appear a Add button, below the item. Clicking on this Add button  is going to add a new slot for another Agent below, instead in the right, check the images

**Comment by gorums** [comment]
@YanetABUC I think we can remove the step where we select which is going to be the first Agent and the agents that we are going to include in the pipeline. We can do both steps here in one step. 

When you click 'New Pipeline', is going to show the first slot empty to allow select the first agent that has to be the same type that the pipeline, after that, you can click in the + button to start adding more Agents in the pipeline, and you cans select wherever you want from the list of all agents that we have.

**Comment by YanetABUC** [comment]
@gorums This request is included in a few tickets. I assigned them to you to review

**Comment by YanetABUC** [comment]
This scenario scenario is working as expected

![image](https://user-images.githubusercontent.com/4720000/119238178-9a6d8a00-bb06-11eb-8c52-8547472dae88.png)

![image](https://user-images.githubusercontent.com/4720000/119238185-a48f8880-bb06-11eb-9280-981675bc0028.png)

![image](https://user-images.githubusercontent.com/4720000/119238196-b2450e00-bb06-11eb-82ca-9e8142d3ee69.png)

**Comment by YanetABUC** [comment]
@lcc1289 This other scenario is not working

I tried to insert agents in all of these sections of the workflow
![image](https://user-images.githubusercontent.com/4720000/119238272-28e20b80-bb07-11eb-84de-01e09286c2cf.png)

![image](https://user-images.githubusercontent.com/4720000/119238290-49aa6100-bb07-11eb-87b5-f60d4a1d3613.png)

**Comment by YanetABUC** [comment]
@gorums What is the expected behaviour if the user tries to add more than 2 agents in the paralel row? Right now there is room for just 2 agents. Trying to figure it out the space will take time

![image](https://user-images.githubusercontent.com/4720000/119238433-e79e2b80-bb07-11eb-9c9f-f370919a45ee.png)

**Comment by YanetABUC** [comment]
Not completly working as expected....Now, I can insert several agents, but all of them will appear at the end, not in the selected position

![image](https://user-images.githubusercontent.com/4720000/119770824-579f0f80-be82-11eb-97c8-fedcb3e5d6f8.png)

![image](https://user-images.githubusercontent.com/4720000/119771064-b49ac580-be82-11eb-8110-1d4f947397dd.png)
