### ISSUE TITLE
Home - Target List - Delete target

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#25]
When user clicks on the 3 dots icon, a submenu will appear. Submenu will contain only one option: Delete. When client clicks option Delete, a confirmation popup will appear, and the user will need to write the name of the selected target as a confirmation

**Step 1**
![image](https://user-images.githubusercontent.com/4720000/103158749-ecdc9180-4786-11eb-9739-fb4138562ac0.png)

**Step 2**
![image](https://user-images.githubusercontent.com/4720000/103158743-e0583900-4786-11eb-94c8-58b857bcba1f.png)

**Step 3 - Confirmation popup** (Delete button will have the same style than the others (with round corners), background color will be #FF4545 and font color will be white)
![image](https://user-images.githubusercontent.com/4720000/105577758-203c1d00-5d41-11eb-8a8a-12a04c5cb0b8.png)

After entering the correct name for the target to be deleted, if user clicks Delete, in the confirmation popup, the target will be deleted from the target list in home and the confirmation popup will be closed.

If user clicks Cancel button in the confirmation popup, the popup will be closed

A notification popup will appear after this action, even if it was successful or not

**Comment by gorums** [comment]
In the modal we the name of the Target
Ex. "Are you sure you want to delete the target MyTargetName?"

**Comment by YanetABUC** [comment]
Working as expected

![image](https://user-images.githubusercontent.com/4720000/107439561-df415800-6af7-11eb-8224-362ff7b164bb.png)

![image](https://user-images.githubusercontent.com/4720000/107439585-e9fbed00-6af7-11eb-8b80-292e91518ed1.png)

![image](https://user-images.githubusercontent.com/4720000/107439626-f5e7af00-6af7-11eb-8485-652f326c193e.png)
