### ISSUE TITLE
Allow selection of an event on Pipeline Settings popup

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#266]
Allow the selection of an event and update the date, will be helpful for users

1. In Pipeline Settings popup, create more that 3 scheduled events
2. Select the second evento
3. Try to update the date by picking another date in the calendar
Current result: Notice that the date will change on the last element of the list and not in the selected element

Expected result:
1. Allow the user to change the date on the selected event

@gorums We need your input here to decide which will be the best option

_Originally posted by @YanetABUC in https://github.com/reconness/reconness-frontend/issues/261#issuecomment-849348765_

**Comment by gorums** [comment]
@YanetABUC I think that the option 2 is the best choice

**Comment by YanetABUC** [comment]
![image](https://user-images.githubusercontent.com/4720000/128623613-be6f28a7-072c-4ff6-82fa-67781a844427.png)
