### ISSUE TITLE
Home - Target List

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#27]
- Target list section will list last 10 created targets or alphabetical by name of the "order by" option changed to "By Name"
- Clicking in a Target name, in section Target List in Home page, will redirect the user to the details page of the selected target

**Comment by gorums** [comment]
- Target list section will list last 10 created targets or alphabetical by name of the "order by" option changed to "By Name"

**Comment by YanetABUC** [comment]
Working as expected
![image](https://user-images.githubusercontent.com/4720000/107439384-94bfdb80-6af7-11eb-8632-7257f8ec6b67.png)
