### ISSUE TITLE
In src/views/TargetsDetailsView.vue

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#342]
we can obtain this data from the store, avoid hard coding here

![image](https://user-images.githubusercontent.com/4720000/128623113-2df41345-a401-44d7-a065-991cb61be49d.png)

**Comment by gorums** [comment]
inside optionBar we have data like 
``` 
...
xaxis: {
          categories: [21, 22, 53, 80, 443, 62],
...
seriesBar: [{
        name: 'series-1',
        data: [62, 44, 38, 50, 78, 57]
      }],
...
```
that we are using to render the chart,
we can get that from the store and then in the integration get that from the backend
