### ISSUE TITLE
In src/components/Target/TargetForm.vue

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#343]
1. `this.validators.blank.name = this.target.name === ''`
![image](https://user-images.githubusercontent.com/4720000/128623139-11b6fd3b-505a-455f-a004-51463b8cf8f5.png)

2. `this.validators.blank.rootDomains = this.target.rootDomains.length === 0`
![image](https://user-images.githubusercontent.com/4720000/128623147-6179ce8c-130e-42ba-8449-5f9cb4b4d5f1.png)

3. the same here
![image](https://user-images.githubusercontent.com/4720000/128623158-46a602cb-f305-4a16-8862-f9d1b25a2844.png)

4. the same here
![image](https://user-images.githubusercontent.com/4720000/128623164-e366a258-0071-44c3-ba2a-33ef802e8982.png)

5. the same here
![image](https://user-images.githubusercontent.com/4720000/128623175-9d311f21-2915-4228-bc16-7ca9362c0037.png)

6. the same here
![image](https://user-images.githubusercontent.com/4720000/128623180-efc8649e-4b35-47b8-929a-54fe57a24e72.png)

7. the same here
![image](https://user-images.githubusercontent.com/4720000/128623185-9d3597ac-bd83-4edf-8db8-02845488058d.png)

8. the same here
![image](https://user-images.githubusercontent.com/4720000/128623189-9390f9a6-f435-4c08-966d-91cfe7a93baa.png)

--
Reported in: https://github.com/reconness/reconness-frontend-codereview/pull/1#discussion_r675279396, https://github.com/reconness/reconness-frontend-codereview/pull/1#discussion_r675279485, https://github.com/reconness/reconness-frontend-codereview/pull/1#discussion_r675279535, https://github.com/reconness/reconness-frontend-codereview/pull/1#discussion_r675279568, https://github.com/reconness/reconness-frontend-codereview/pull/1#discussion_r675279656, https://github.com/reconness/reconness-frontend-codereview/pull/1#discussion_r675279691, https://github.com/reconness/reconness-frontend-codereview/pull/1#discussion_r675279712, https://github.com/reconness/reconness-frontend-codereview/pull/1#discussion_r675279760

**Comment by gorums** [comment]
I dont remember why I put this comment
