### ISSUE TITLE
Settings menu

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#36]
![image](https://user-images.githubusercontent.com/4720000/103471004-fb571a00-4d3f-11eb-8d7c-089c63629729.png)

![image](https://user-images.githubusercontent.com/4720000/103593243-ed79d400-4eba-11eb-9e10-d1d4615a8fdd.png)

![image](https://user-images.githubusercontent.com/4720000/103471013-280b3180-4d40-11eb-8222-213ffc497c09.png)

- In the general header bar, Settings will be a link to the Setting page. Same link that appear in the main menu.
- In the main menu, when user clicks on Settings item, the element will be expanded and display Notifications and Logs as subitems

**Comment by gorums** [comment]
Settings SubMenu for now
- Notifications
- Logs

**Comment by YanetABUC** [comment]
@lcc1289 Please, check this in following pages. This is also happening with User menu

![image](https://user-images.githubusercontent.com/4720000/119236645-36df5e80-bafe-11eb-8440-9f0b08f31da5.png)

Targets list
Target Details page
Root domain details page
Subdomain Details page
Agents list
Pipeline pages

**Comment by YanetABUC** [comment]
This part is working as expected
![image](https://user-images.githubusercontent.com/4720000/119236663-51193c80-bafe-11eb-8999-c64387e25a1a.png)

![image](https://user-images.githubusercontent.com/4720000/119236684-6e4e0b00-bafe-11eb-9374-44bfa6de0f9f.png)

**Comment by YanetABUC** [comment]
Working as expected
![image](https://user-images.githubusercontent.com/4720000/119284494-7775cf80-bc05-11eb-89d5-a71d059fc2f7.png)
