### ISSUE TITLE
Design of Notifications menu and page

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#37]
### Mockup

![image](https://user-images.githubusercontent.com/4720000/103471089-2130ee80-4d41-11eb-8815-af953edecfb7.png)

![image](https://user-images.githubusercontent.com/4720000/103471161-4540ff80-4d42-11eb-90a3-96d2b076f4e1.png)

![image](https://user-images.githubusercontent.com/4720000/103471218-33139100-4d43-11eb-9270-8c22d5023299.png)

### Specifications

- In the general header bar, clicking the notification icon will open an small popup with a list of the 5 most recently notifications and a link to view all Notifications
- Add a circle badge with a number at the top right corner of the icon. That will mean the number of unread notifications received by the user. If the number is greater than 10, the text inside the badge will be "**+9**". If the number is equals to 0, the red badge will disappear. Any time the user clicks on the notification icon, the number will be reseted to 0, so the badge will disappear.
- Clicking on link "View all notifications" will open the Notifications page
- **_Notifications page needs to be defined_**

**Comment by gorums** [comment]
Notifications page show the list of all notifications dynamic scrolling

**Comment by YanetABUC** [comment]
![image](https://user-images.githubusercontent.com/4720000/128621829-7be9b0b8-bc19-4c12-91de-9a689546c145.png)

![image](https://user-images.githubusercontent.com/4720000/128621835-16d1510b-953b-4a68-9bce-a1acb1fcc158.png)
