### ISSUE TITLE
User menu

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#38]
### Mockups
![image](https://user-images.githubusercontent.com/4720000/103471324-9c47d400-4d44-11eb-911e-78c21218ae10.png)

![image](https://user-images.githubusercontent.com/4720000/103593907-b86e8100-4ebc-11eb-88ee-291fb5dd1c01.png)

### Specifications
- Clicking in either username or user photo, will display a popup with the following options: My account, Sign out
- Option My account will open a page with title My Account. In this page the user will be able to change his name and lastname, email and photo.  (described in #39 )
- Option Sign out will log out the user and close the current user session

**Comment by gorums** [comment]
- We are going to have Logs Submenu on Settings.
- For now you can not change the password from the UI

**Comment by YanetABUC** [comment]
@lcc1289 Please, check this in following pages. This is also happening with Settings menu

![image](https://user-images.githubusercontent.com/4720000/119236484-51fd9e80-bafd-11eb-8709-0b06a9b2afec.png)

![image](https://user-images.githubusercontent.com/4720000/119236506-6772c880-bafd-11eb-800b-bdbb858aa139.png)

![image](https://user-images.githubusercontent.com/4720000/119236525-81141000-bafd-11eb-8175-1aae886e15fb.png)

![image](https://user-images.githubusercontent.com/4720000/119236535-912bef80-bafd-11eb-9d32-49e3727fbf4b.png)

![image](https://user-images.githubusercontent.com/4720000/119236543-9be68480-bafd-11eb-88ae-612069fedc4b.png)

![image](https://user-images.githubusercontent.com/4720000/119236572-bfa9ca80-bafd-11eb-82fd-2a364fd67110.png)


- Targets list
- Target Details page
- Root domain details page
- Subdomain Details page
- Agents list
- Pipeline pages

**Comment by YanetABUC** [comment]
Working as expected

![image](https://user-images.githubusercontent.com/4720000/119284396-3a114200-bc05-11eb-906a-d4dd92429bdd.png)
