### ISSUE TITLE
My account page

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#39]
-- to be defined --

**Comment by gorums** [comment]
My account page. In this page the user will be able to change his name and lastname, email, photo

**Comment by YanetABUC** [comment]
![image](https://user-images.githubusercontent.com/4720000/130090941-3e03aa00-8998-490f-9d13-d7b9b1716e4b.png)

![image](https://user-images.githubusercontent.com/4720000/130091095-75b23c27-42c8-45d5-9f98-c588d2bbcf64.png)
