### ISSUE TITLE
Design of Logs page

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#40]
### Mockups

![image](https://user-images.githubusercontent.com/4720000/103593243-ed79d400-4eba-11eb-9e10-d1d4615a8fdd.png)

![image](https://user-images.githubusercontent.com/4720000/103471440-30666b00-4d46-11eb-959f-d5364c7bac86.png)

![image](https://user-images.githubusercontent.com/4720000/103471446-378d7900-4d46-11eb-889c-0da62ee65175.png)

![image](https://user-images.githubusercontent.com/4720000/103471451-43793b00-4d46-11eb-86e1-9f252f8a6ff8.png)

![image](https://user-images.githubusercontent.com/4720000/103471453-4d02a300-4d46-11eb-8e86-d2791b50f28b.png)

![image](https://user-images.githubusercontent.com/4720000/103471455-54c24780-4d46-11eb-9bfa-7057ac66dd98.png)

### Specifications
- User clicks option Logs in User menu in general header bar
- Logs page will open. The page contains a combobox with the names of the logs files generated by Reconess
- If user selects an option from the combobox, then the content of the file will appear in the textarea with an scroll to read all its content
- If user clicks Clear button, a confirmation popup will appear. If user confirms to clear the logs file, all the content of the log file will be deleted and the file will be empty

**Comment by gorums** [comment]
- Logs is a Settings SubMenu not a MyAccount Submenu

**Comment by YanetABUC** [comment]
![image](https://user-images.githubusercontent.com/4720000/130090708-e2f12bab-3511-4a19-b4c7-a1794a1e5774.png)
