### ISSUE TITLE
Design of Welcome/Login page

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#41]
### Mockups
![image](https://user-images.githubusercontent.com/4720000/103471629-1af24080-4d48-11eb-8a36-8c44df1cc190.png)

![image](https://user-images.githubusercontent.com/4720000/103471669-a1a71d80-4d48-11eb-884e-527874b210d1.png)

### Specifications
- User will provide his username and password in order to log into the system
- A Forgot my password link will be included in the page (defined in #42 )
- Both username and password are required. If any of those values is not correct the system will display the following error message: "Invalid credentials. Please try again"

**Comment by gorums** [comment]
"Forgot my password" is going to open a new tab with this link
https://docs.reconness.com/getting-started/installation#login-inside-reconness

**Comment by YanetABUC** [comment]
https://xd.adobe.com/view/ea33f439-da88-4a06-af50-6baac464f863-bf60/

![image](https://user-images.githubusercontent.com/4720000/130089545-e1ad27c3-e9b5-470f-8e90-792e0cdebf49.png)
