### ISSUE TITLE
[FEATURE] Notifications

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#418]
### Mockups
![image](https://user-images.githubusercontent.com/4720000/139616169-1893875f-8d52-4771-ad4a-d72994642b51.png)

![image](https://user-images.githubusercontent.com/4720000/141218107-6926191f-5355-428b-81fe-bd37b6922342.png)

![image](https://user-images.githubusercontent.com/4720000/139616296-46c60fef-f9f2-4083-90f1-e9e147530355.png)

![image](https://user-images.githubusercontent.com/4720000/139616354-db4aecb5-e73b-47e7-b227-9761364dfa25.png)

![image](https://user-images.githubusercontent.com/4720000/139617470-66851f87-b855-4a13-b18c-4ffe6eb4e316.png)

**Status icons**
_Successful_ 
![image](https://user-images.githubusercontent.com/4720000/139616455-8aec6e89-2c5c-427c-a8ab-a65e640dcbb5.png)

_Failed_
![image](https://user-images.githubusercontent.com/4720000/139616487-88024b5b-de85-4a65-a54b-60daa285a14d.png)

_In progress_
![image](https://user-images.githubusercontent.com/4720000/139616501-1c20f31d-8e34-4c1b-becc-9f37e078f6db.png)

### Prototype
https://xd.adobe.com/view/d9ed934f-460d-4380-a5a3-b25e48e782d9-8cbe/

### Acceptance Criteria
1. A notification will be generated everytime an agent or pipeline starts to run
2. The number of new notifications will appear in a red round badge at the top right corner of Notifications icon, in Top Main Menu
3. Clicking the notifications icon, will display the Notification popup
- Popup contains a fixed header and fixed footer.
- Header will include a Clear All linkbutton. 
   - Clear all button will remove notifications from DB. A confirmation popup will be prompted to query the user if he/she, wants to remove today, last week or all notifications. User will pick one option and then tnotifications that match with the option selected will be permanently deleted
- Content inside the popup is scrolleable. See the effect in the prototype
- Footer will contain a link to redirect user to the Notifications Center page
- This popup will display only the notifications generated Today and Yesterday
- New notifications will be contained between 2 blue bars
- Few seconds after opening the notifications popup, all notifications will change its status to "read" and red badge that appear in the Notifications popup will dissapear
4. Notification Center page
- Notifications info will be displayed in a table with the following columns: Status, Description, Date (date and time)
- Content will be splitted by sections: Today, Yesterday, Older
- Section will include a fixed footer at the bottom of the page. Footer will display the total number of notifications listed
- Content is scrolleable
- Notice that New notifications style is different from the old notifications style

**Comment by YanetABUC** [comment]
@gorums Some questions or concerns:
- I'm not sure if the functionality of Clear all link button were described as expected
- I'm not sure how a notification will not be New anymore. It will be by a manual action? it will be automatic?
- There are 3 dots near every item in the Notifications popup. What actions are included there? should we remove them?

![image](https://user-images.githubusercontent.com/4720000/139617801-04cf8a54-00e1-4139-aebe-7c195bfa3c90.png)

**Comment by gorums** [comment]
@YanetABUC 
I'm not sure if the functionality of Clear all link button were described as expected
> Clear all is to remove those notification history from DB, the problem here is: Do you want to remove today, last week or all history. That means that we need to open a conformation modal with those options.
I'm not sure how a notification will not be New anymore. It will be by a manual action? it will be automatic?
> After open the notifications popup is going to move all to `read`
There are 3 dots near every item in the Notifications popup. What actions are included there? should we remove them?
> remove that for now
