### ISSUE TITLE
[FEATURE] Edit a Wordlist file

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#421]
### Mockups
**Old version examples**
![WhatsApp Image 2021-11-05 at 9 59 28 AM](https://user-images.githubusercontent.com/4720000/140540962-0edc8c2c-310a-477b-a697-cd6ccf158475.jpeg)
![WhatsApp Image 2021-11-05 at 9 54 16 AM](https://user-images.githubusercontent.com/4720000/140540966-ef8d3523-8d26-4cbe-9a3e-5dcb0462138a.jpeg)

### Acceptance Criteria
1. A Wordlist file will be editted as Github edits files
2. Edit option will be visible only if the file size is less than 20 MB
3. User will be able to open the Wordlist file in Edit mode by clicking on the filename. The name will be a link for edit the file, only if the file size is less than 20 MB, otherwise, the filename will appear as plain text
4. If the file is candidate for edition, there will be a tooltip in its name with the text: "Click here for edit this file"
3. After clicking Edit, the content of the file will appear in an Editor or big textarea, the file can be eddited by the user and then saved

**Comment by YanetABUC** [comment]
Working as expected, as documented in https://github.com/reconness/reconness-frontend/issues/446#issuecomment-1031976838

**Comment by gorums** [comment]
@YanetABUC Duplicate ticket https://github.com/reconness/reconness-frontend/issues/500

**Comment by gorums** [comment]
@YanetABUC  instead 20 MB we are going to use 5 MB

**Comment by YanetABUC** [comment]
This ticket is duplicated, hence I'm closing it
