### ISSUE TITLE
Target list - Header

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#44]
### Mockup
![image](https://user-images.githubusercontent.com/4720000/103471912-1d569980-4d4c-11eb-949e-b0a036f5843d.png)

### Specifications
- Options:
1. Import target
2. Filters by color (Equals to agent)
3. Sort by Name and creation date (Equals to agent)
4. View mode: List view, Mosaic view (Equals to agent)

- Import target: The option will open a browser open dialog. User will be able to search for a .json file and import its content in the target section
This action will be simulated as the import operation will require some API endpoints

![image](https://user-images.githubusercontent.com/4720000/105580827-5cc54400-5d54-11eb-9171-c495024f345a.png)

**Comment by gorums** [comment]
is not a .csv file, is going to be a .json file

**Comment by YanetABUC** [comment]
Working as expected
![image](https://user-images.githubusercontent.com/4720000/107440129-c5544500-6af8-11eb-8b6e-e1c4fa66c5ed.png)
