### ISSUE TITLE
[BUG] Incorrect alignment of triangle character with text in Agents details popup

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#465]
**Describe the bug**
Incorrect alignment of triangle character with text in Agents details popup

**To Reproduce**
1. Go to Agents section
2. Click on any agent item Details link

**Expected behavior**
- Align triangle character with the top of the text
- If there is a row with no data, do not display the tiangle character

**Screenshots**
![image](https://user-images.githubusercontent.com/4720000/153721010-cd7ea83b-7d0b-4220-827f-923ff18339da.png)

![image](https://user-images.githubusercontent.com/4720000/153721046-f94dd49e-fd97-4a8b-bb7d-0819afbf483a.png)

**Comment by gorums** [comment]
@YanetABUC I think this is done

**Comment by YanetABUC** [comment]
Found this bug

![image](https://user-images.githubusercontent.com/4720000/162555191-056fb6bd-520c-426c-985b-57e088cea1f6.png)

**Comment by YanetABUC** [comment]
![image](https://user-images.githubusercontent.com/4720000/164948466-36b7dfe5-bdc9-4c03-a3e5-8bcde4720501.png)

![image](https://user-images.githubusercontent.com/4720000/164948481-919996d6-33d2-4aef-b253-773be5903ea9.png)
