### ISSUE TITLE
[BUG] Typo in agent delete popup

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#466]
**Describe the bug**
Delete Agent poup has some typos. It displays "Target" instead of "Agent". The same happens in multiple agents delete popup

**To Reproduce**
1. Go to Agent list
2. Click on Delete button, to delete an agent
3. It displays "target" instead of "agent"
4. The same happens in multiple agents delete popup

**Expected behavior**
Rename "target" word for "agent"

**Screenshots**
![image](https://user-images.githubusercontent.com/4720000/153721450-2628b1e6-2a90-4a87-b014-7818a2fad148.png)

![image](https://user-images.githubusercontent.com/4720000/153721652-cc688d54-6797-4757-9bef-2ed6d9c2cfad.png)

**Comment by gorums** [comment]
@YanetABUC  I think this is done
