### ISSUE TITLE
Create target

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#47]
### Mockup
![image](https://user-images.githubusercontent.com/4720000/103488065-74ea1900-4dcf-11eb-901d-580090b89c70.png)

![image](https://user-images.githubusercontent.com/4720000/103488261-b5966200-4dd0-11eb-8f9d-ec617022defe.png)

![image](https://user-images.githubusercontent.com/4720000/103488279-f4c4b300-4dd0-11eb-9530-b98a45a60c39.png)

![image](https://user-images.githubusercontent.com/4720000/103488213-56385200-4dd0-11eb-810a-6f9170fd375e.png)

### Specifications
- Only the target name, at least one root domain and the color are required. Done button will be enable just when all required elements have data
- Target name input will have same behavior than Agent name in the New/Edit Agent popup
- In input Bug Bounty Program URL, the system will also use an url validator
- Add a Delete button at the bottom left corner of the popup, same as in New/Edit Agent popup. All buttons will be aligned in the same row (#50 )
- A notification popup will appear after this action, even if it was successful or not

**Comment by gorums** [comment]
Bug Bounty Program URL, In Scope and Out of Scope are optionals

**Comment by YanetABUC** [comment]
Working as expected
![image](https://user-images.githubusercontent.com/4720000/107458170-2db31e80-6b19-11eb-93cb-fc473e0b21fd.png)
