### ISSUE TITLE
Edit target

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#48]
### Mockups
![image](https://user-images.githubusercontent.com/4720000/103488328-39504e80-4dd1-11eb-9027-14942fdbbfd9.png)

![image](https://user-images.githubusercontent.com/4720000/103488348-5dac2b00-4dd1-11eb-8f9b-2ddd3d74b100.png)

![image](https://user-images.githubusercontent.com/4720000/103488213-56385200-4dd0-11eb-810a-6f9170fd375e.png)

### Specifications
- Only the target name, at least one root domain and the color are required. Done button will be enable just when all required elements have data
- Target name input will have same behavior than Agent name in the New/Edit Agent popup
- In input Bug Bounty Program URL, the system will also use an url validator
- Add a Delete button at the bottom left corner of the popup, same as in New/Edit Agent popup. All buttons will be aligned in the same row (#50 )
- A notification popup will appear after this action, even if it was successful or not

**Comment by gorums** [comment]
Only the target name, at least one root domain and the color are required

**Comment by YanetABUC** [comment]
Reopening this ticket due to following bugs:

### Adding a new root domain to the target caused that only the new added element is displayed in the target list item, mosaic view:
**Steps to reproduce**:
1. Click on Edit Target
![image](https://user-images.githubusercontent.com/4720000/108017813-70726c00-6fdb-11eb-90a7-26e9ccf21b16.png)
![image](https://user-images.githubusercontent.com/4720000/108017824-7ec08800-6fdb-11eb-86cd-16627ab4bd2e.png)

2. Add a new root domain to the list and click Done button
![image](https://user-images.githubusercontent.com/4720000/108017861-95ff7580-6fdb-11eb-9fd3-48ddb989970f.png)
![image](https://user-images.githubusercontent.com/4720000/108017907-c6471400-6fdb-11eb-9580-bda90d70bd02.png)

### In list view mode Edit link is not working
Clicking on Edit menu iten, in target list item, List mode, do not display the Edit Target popup
![image](https://user-images.githubusercontent.com/4720000/108017958-f1c9fe80-6fdb-11eb-90f1-7bc1729a2ae8.png)

**Comment by YanetABUC** [comment]
Now is possible to edit from Target section in List mode
![image](https://user-images.githubusercontent.com/4720000/108258444-a0c62180-7125-11eb-8038-7c102ca7f030.png)

Adding a new root domain is working as expected
![image](https://user-images.githubusercontent.com/4720000/108258620-d8cd6480-7125-11eb-9fc5-7997323e35b7.png)
