### ISSUE TITLE
[FEATURE] We are not saving the CreateBy on the backend side, Gorums should come out here

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#480]
### Mockups
![image](https://user-images.githubusercontent.com/4720000/154599017-5814ec9d-991e-479a-8b5f-82a235b8b7fc.png)

### Acceptance Criteria
1. [Criteria list]

**Comment by gorums** [comment]
@YanetABUC We need to use the username from the auth user in the backend, installing new agent and creating one manually

**Comment by YanetABUC** [comment]
![image](https://user-images.githubusercontent.com/4720000/162555334-a6ac9181-6ec0-43be-8b19-448db17a22c3.png)
