### ISSUE TITLE
Display API message errors when creating an Agent

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#491]
If creating a new Agent gives me an error, for example I am using a name of an agent that exists, the modal closes and tells me that there was an error "editing the process" without further details, instead of showing me the error and not closing me the modal to correct the possible error and re-intern save.
That is what the backend returns, that message should be shown as part of the error, and of course not close the modal itself with the Agent Edit.
![image](https://user-images.githubusercontent.com/4720000/154603286-6cd13775-6f28-4ebd-9065-e5bdb290835b.png)

**Comment by gorums** [comment]
@YanetABUC duplicate see #492
