### ISSUE TITLE
Show enable or disable the Add button in the reference/home page

### ISSUE THREAD

**Issue by gorums** [reconness/reconness-frontend#504]
### Mockups
Now we dont know if the add button is enable or disable, we need to show in some way that behavior, we can modify the button border or the font(bold).

![image](https://user-images.githubusercontent.com/1503645/155364181-3738cc46-b7ab-4805-906d-04ef8c75fcb7.png)

**Comment by YanetABUC** [comment]
@gorums What do you expect as a good solution here? Default style button is as appear in the app right now

**Comment by YanetABUC** [comment]
Change this button style
