### ISSUE TITLE
Comments in target details page

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#51]
### Mockups
![image](https://user-images.githubusercontent.com/4720000/103490535-082c4a00-4de2-11eb-949e-90a2399130e5.png)

![image](https://user-images.githubusercontent.com/4720000/103490538-1a0ded00-4de2-11eb-9b61-0f4df6e2e46a.png)

![image](https://user-images.githubusercontent.com/4720000/105596021-33f37d80-5d59-11eb-8662-1ee112b98753.png)

![image](https://user-images.githubusercontent.com/4720000/105598567-e3c8eb00-5d59-11eb-837b-d90b90ea0aa8.png)

### Specifications

1. Clicking on Comments icon, in the header bar of a target details page, will expand a collapsible side bar
2. Comments sidebar will be closed only when user clicks anywhere else outside the bar
3. At the top of the sidebar there will be an editor to add new comments

- Send button will be enabled if text input has text
- Cancel button will clear the text in the text input but it won't collapse the comments bar.

4. Bellow the editor it will appear a list with all comments. 

- The list will have "Comments List" as a title and the style will be the same as Target List in homepage
- Sort by will display a menu with options "Username" and "Created". Username will order the comments by username and Created will order the comments by creation date (DESC, newest comments will appear at the top of the list)
- The list will contain an scroll if neeaded. The default sort mode is by creation date, DESC (newest comments will appear at the top of the list)
- Every comment item will contain the whole comment text, the username of the user who created the comment, the creation date for the comment (date format: yyyy-MM-dd) and a Delete button

5. Clicking on Delete button will display a confirmation popup.
6. If user confirms the delete action, the comment will be deleted and the user will see a notification popup (if the action was successful or not)

**Comment by gorums** [comment]
We are going to show all the comments add to that target order by created date.
We are going to show the comment + (username and date).
@YanetABUC  There is not an example in the mockout on xd.adobe that we can see a comment and how we are going to show that.

**Comment by YanetABUC** [comment]
The default sort mode is by creation date DESC, meaning the the newest comment (las created) will appear at the top of the list

![image](https://user-images.githubusercontent.com/4720000/108027516-ef719f80-6fef-11eb-98da-6f42f46bea7f.png)

**Comment by YanetABUC** [comment]
![image](https://user-images.githubusercontent.com/4720000/108785605-60a4db80-7537-11eb-974a-37c6a2627661.png)
