### ISSUE TITLE
Integrate services for Export Target in Target Details page

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#524]
Integrate services for Export Target in Target Details page

![image](https://user-images.githubusercontent.com/4720000/164950604-1f72f2aa-1017-4047-91ec-0d4655716014.png)

**Comment by YanetABUC** [comment]
@gorums We need to know in which format data will be exported: CSV, JSON, PDF?

Also we need to know what data will be exported.

**Comment by gorums** [comment]
@YanetABUC we are exporting to json. All the data relative to the rootdomain
