### ISSUE TITLE
Agent (27): Align buttons in a row

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#554]
Put the Edit button at the end of the Delete button, and give it more space to make it look clear

![image](https://user-images.githubusercontent.com/4720000/167062766-7cba595f-b28a-4f46-9bfa-ad22c75bfc27.png)

If needed, replace the button text with an icon and include a tooltip with the replaced text

**Comment by YanetABUC** [comment]
@gorums Maybe is a good idea to use buttons with icons and a tooltip here. Thoughts?

**Comment by gorums** [comment]
@YanetABUC  I love that idea. Lets do it
