### ISSUE TITLE
Use proper service for delete one agent

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#568]
Currently same api service is used for delete one agent and for delete multiple agents. Let's use the apropiate service for delete one agent

**Comment by gorums** [comment]
@YanetABUC @lcc1289 this is the endpoint to delete one agent
DELETE api/agents/{agentName}

**Comment by YanetABUC** [comment]
Resolved!
![image](https://user-images.githubusercontent.com/4720000/170920726-1114761a-9916-47a8-9961-71d38b03e59e.png)
