### ISSUE TITLE
Search and filter subdomains in root domain details page

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#57]
### Mockup
![image](https://user-images.githubusercontent.com/4720000/103491112-90145300-4de6-11eb-8ccd-3c2a60830dd7.png)

### Specifications
1. - The Filter by list will include following options: **Label**, **Service**, **Port**, **Agent** and **Date**. By default there will be no filter selected.
2. User types a query in Search input and selects an option from the Filter by list
3. The search action will be executed when the user hits Enter key or when the user selects an option from the Filter by dropdown list. 
4. The process will be as follow:
- If there is no filter selected in Filter by dropdown list, then the query will be executed against the **name of a subdomain**. The query can match partially or completely.
- In Filter by dropdown list, if **Label** option is selected, then the query will be executed against the **labels associated to a subdomain** (the label checkbox will appear as checked). The query can match partially or completely. Every subdomain will contain a list of labels. The list can be empty
- In Filter by dropdown list, if **Service** option is selected, then the query will be executed against the **name of the services associated to a subdomain**. The query can match partially or completely. Every subdomain will contain a list of services. The list can be empty
- In Filter by dropdown list, if **Port** option is selected, then the query will be executed against the **open ports associated to a subdomain**. The query can match partially or completely. Every subdomain will contain a list of open port. The list can be empty
- In Filter by dropdown list, if **Agent** option is selected, then the query will be executed against the **name of the agents associated to a subdomain**. The query can match partially or completely. Every subdomain will contain a list of agents. The list can be empty.
- In Filter by dropdown list, if **Date** option is selected, then the query will be executed against the **creation date of a subdomain**
5. The list of subdomains will display the results of the search action.

**Comment by YanetABUC** [comment]
@gorums Could you describe how will be the filter action? There are some options in the Filter by list and I need more information to describe the process. Will it be the same process for all the options?

**Comment by gorums** [comment]
@YanetABUC We are going to have those filters options:
- Label, Service, Port, Agent and Date

basically the idea is that you can put a string and select a filter options, and we are going to search using that string and the option selected
Ex.
search: 443, filter option: Port

**Comment by gorums** [comment]
@YanetABUC  we are not going to have **Label** by default, no filter by default. If we dont have selected filter we are going to search using the subdomain's names

**Comment by YanetABUC** [comment]
@gorums Please, check again and give me your feedback

**Comment by YanetABUC** [comment]
These scenarios are working

![image](https://user-images.githubusercontent.com/4720000/112804125-40ce6f00-9031-11eb-85cc-142050f854b9.png)

![image](https://user-images.githubusercontent.com/4720000/112804212-5cd21080-9031-11eb-9ac1-40a204d6d2c9.png)

![image](https://user-images.githubusercontent.com/4720000/112804261-6fe4e080-9031-11eb-8c3e-f9bb1b048293.png)

**Comment by YanetABUC** [comment]
Searching by Agents is causing issues

![image](https://user-images.githubusercontent.com/4720000/112805332-b2f38380-9032-11eb-8174-c5020eb8be76.png)

![image](https://user-images.githubusercontent.com/4720000/112805372-bedf4580-9032-11eb-8cbe-4fd5aecfaa9a.png)
