### ISSUE TITLE
[FEATURE] Add functionality to Export all Subdomains feature, Root Domain details page

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#580]
Add functionality to Export all Subdomains feauture, Root Domain details page. Info will be exported to a CSV file.

### Mockups
![image](https://user-images.githubusercontent.com/4720000/173252218-6e404b8c-7d2d-40a2-adac-0ef18ae7781c.png)

**Comment by gorums** [comment]
@YanetABUC is not a json, is a list of subdomains separate by ',' is a csv file

**Comment by gorums** [comment]
@YanetABUC export all subdomain generate a csv file with a list of subdomains names separate per ','. try to open in like a txt to see the data, and let me know
