### ISSUE TITLE
[FEATURE] Integrate services in Search and Filter by feature

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#582]
Integrate services in Search and Filter by feature, Root Domain details page

### Mockups
![image](https://user-images.githubusercontent.com/4720000/173252438-f57d3ed5-2899-40dc-be2e-42bfd16a6ef2.png)

**Comment by gorums** [comment]
@YanetABUC we can add a couple there, but basically a services is for example http, ssh

**Comment by gorums** [comment]
@YanetABUC lets do this next sprint
