### ISSUE TITLE
Subdomain details page

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#59]
### Mockups
![image](https://user-images.githubusercontent.com/4720000/103491180-2e081d80-4de7-11eb-84b0-309812e0c904.png)

![image](https://user-images.githubusercontent.com/4720000/110287128-a20f9f00-7fab-11eb-9570-d148c24f5bd7.png)

### Specifications
1. Clicking on the arrow button that appear in the last column of the subdomains list, will redirect the user to the subdomain details page.
2. In the Dashboard section:
- Value for IP field, will be generated automatically. It will come from the DB, only the agents can modify that. This field is not editable.
- Value for Agents field will be generated automatically.  It  is the list of different agents that we ran against the subdomain. This field is not editable.
- IP and Agents values are the same that appear in the subdomains list, in a Root Domains Details page. The only exception is that in the subdomain list, we will display a comma separated list with the name of the last 3 agents executed on the subdomain.

**Comment by YanetABUC** [comment]
@gorums I have a question, do we need to display, in Agents tab, the whole list of Agents or only the agents of type Subdomain? If yes, where should we display the agents of type Target?

**Comment by YanetABUC** [comment]
@gorums 
- In the Dashboard section of a Subdomain Details page, appear a comma-separated list of agents, is there any rule to populate that field? Is it an editable field? 
- Is is editable the IP field?
- In the subdomains list, in a Root Domain Details page, appear a comma separated list of Agents, how can we populate that list?

**Comment by gorums** [comment]
> @gorums
> 
> * In the Dashboard section of a Subdomain Details page, appear a comma-separated list of agents, is there any rule to populate that field? Is it an editable field?

@YanetABUC  That is the list of agents that we ran against the subdomain, Ex We ran NMAP yesterday, then we are going to show NMAP as one of the Agents that we ran before against the subdomain

> * Is is editable the IP field?

@YanetABUC  Nop, that came from the DB, only the agents can modify that
> * In the subdomains list, in a Root Domain Details page, appear a comma separated list of Agents, how can we populate that list?

That came from the DB, the name of the field is ``AgentRanBefore``

**Comment by YanetABUC** [comment]
@gorums I updated this story, plesae, check again and give me your feedback.

**Comment by YanetABUC** [comment]
![image](https://user-images.githubusercontent.com/4720000/112793948-62285e80-9023-11eb-8909-ef602b2b12ea.png)
