### ISSUE TITLE
[BUG] Feedback May 1: Error while creating an agent

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#604]
**Describe the bug**
If I try to add a new agent I get this error ticket #501, it has to do with the triggers that we added, it seems that they are not defined, it is not sending that part correctly to the backend

**Screenshots**
![image](https://user-images.githubusercontent.com/4720000/177671803-987a7767-14fc-4a7f-987f-fc8056445a3f.png)

![image](https://user-images.githubusercontent.com/4720000/177672093-c6e57677-9349-4e23-be44-bf6b7a6b646e.png)

![image](https://user-images.githubusercontent.com/4720000/177671882-8afe4bde-50e2-4f81-a4dd-7ef63aa00c0f.png)

**Comment by gorums** [comment]
@YanetABUC @yoanhdez I did a change in the backend, now we can have in the AgentTrigger table all the boolean values can be NULL, maybe that was the issue before
