### ISSUE TITLE
Run agent in root domain

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#89]
### Mockups

![image](https://user-images.githubusercontent.com/4720000/107459829-99e35180-6b1c-11eb-944b-db4ca0c9a6fb.png)

**Agent Execution popup**
![image](https://user-images.githubusercontent.com/4720000/107459683-5688e300-6b1c-11eb-8fbb-e4e9306e0b48.png)

![image](https://user-images.githubusercontent.com/4720000/107461103-e7f95480-6b1e-11eb-96b1-887de42db95a.png)

![image](https://user-images.githubusercontent.com/4720000/107459724-69031c80-6b1c-11eb-8f88-cccd170936a4.png)

![image](https://user-images.githubusercontent.com/4720000/107459770-7d471980-6b1c-11eb-96fd-0373041e0cf8.png)

![image](https://user-images.githubusercontent.com/4720000/107459797-8afc9f00-6b1c-11eb-8828-af695abd85a0.png)

### Specifications
1. When user click on button Run, the Agent Execution popup will appear. 
2. The Agent Execution popup includes:
- A progress bar and a progress circle to display the progress of the execution of the agent in the root domain
- A time indicating how long have been executing the agent
- A button to pause or play the execution
- If  Terminal option is selected, then the user will see the terminal output. 
- If  Logs option is selected, then the user will see the logs generated during the execution of the agent.
- Status of the execution. Possible status are: Running, Paused, Finished 
- Stop button, to stop the execution of the agent. Stop button will also close the popup

3. When the Agent is running, the text of Run button, in the Agents list, will be renamed to Running. If user clicks on Running button, the Agent Execution popup will appear and its content will be updated according with the status of the current execution.
4. The user will be able to close the Agent Execution popup at any time. This won't interrupt the execution of the Agent. If the user closes the Terminal popup, he will be able to open it again by clicking on Running button.
5. If the user wants to Stop the execution of the agent he will need to click on Stop button, in the Agent Execution popup.
6. 2 or more agents can NOT be executed at the same time, so when an Agent is running in the root domain, all other Run buttons will be disabled. Once the execution of the agent is stopped by the user or if the execution finishes, then all Run buttons in the list will be enabled again.

**Comment by gorums** [comment]
check the design

![image](https://user-images.githubusercontent.com/1503645/107161267-8b086d80-6969-11eb-9071-c957d60da7e0.png)

**Comment by gorums** [comment]
![image](https://user-images.githubusercontent.com/1503645/107161277-a07d9780-6969-11eb-9d53-3bd54bc6985e.png)

**Comment by gorums** [comment]
![image](https://user-images.githubusercontent.com/1503645/107161365-46310680-696a-11eb-930c-c92f3674da9a.png)

**Comment by YanetABUC** [comment]
@gorums Please, check this story again

**Comment by gorums** [comment]
@YanetABUC  We dont need Pause option, and we can Run more than one Agent in the same time, if the agent is waiting we are going to show Waiting..., instead Running...
.
Status of the execution. Possible status are: Running, Waiting

**Comment by YanetABUC** [comment]
![image](https://user-images.githubusercontent.com/4720000/113542923-edb56880-95aa-11eb-9fe1-9b4d1ffcc8e9.png)

![image](https://user-images.githubusercontent.com/4720000/113542950-fb6aee00-95aa-11eb-9d47-d590963a3cf8.png)
