### ISSUE TITLE
Feedbacks in PR

### ISSUE THREAD

**Issue by YanetABUC** [reconness/reconness-frontend#96]
- [x] View image below
![image](https://user-images.githubusercontent.com/4720000/106026589-a2a14580-608f-11eb-9ffb-70f8b57e8b12.png)

- [x] View image below
![image](https://user-images.githubusercontent.com/4720000/106026648-b3ea5200-608f-11eb-9792-200258c47b9e.png)

- [x] View image below
![image](https://user-images.githubusercontent.com/4720000/106026681-bea4e700-608f-11eb-8d15-e12bd1c51ca0.png)

- [ ] Another thing. Can we update package.json with the new version of packages that we can use? right now we have 12 PR with new lib version.

**Comment by lcc1289** [comment]
The duplicate code detected was solved by implementing a plugin for the application.  From now on all generic functionalities will be implemented there

**Comment by YanetABUC** [comment]
The update for packages versions will be executed progressively and it's planned per weeks
